"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requerirPermiso } from "@/servicios/autenticacion/requerir-permiso";
import { buscarTrabajadoresParaRegistro } from "@/modulos/registro-diario/consultas/registro-diario.consulta";
import { anularDocumentoClinicoServicio, guardarDocumentoClinicoServicio } from "@/modulos/documentos-clinicos/servicios/documentos-clinicos.servicio";
import { documentoClinicoBorradorSchema, documentoClinicoFinalizarSchema } from "@/modulos/documentos-clinicos/validaciones/documento-clinico.schema";
interface Resultado<T> { exito: boolean; datos?: T; mensaje?: string; erroresCampos?: Record<string, string[]> }
export async function buscarTrabajadoresDocumentoAccion(q: string) { const usuario = await requerirPermiso("documento-clinico.ver"); return buscarTrabajadoresParaRegistro(usuario.id, q); }
export async function guardarDocumentoClinicoAccion(id: string | null, entrada: unknown, finalizar: boolean): Promise<Resultado<{ id: string }>> { try { const u = finalizar ? await requerirPermiso("documento-clinico.finalizar") : await requerirPermiso(id ? "documento-clinico.editar" : "documento-clinico.crear"); const datos = (finalizar ? documentoClinicoFinalizarSchema : documentoClinicoBorradorSchema).parse(entrada); if (!datos.trabajadorId || !datos.fechaDocumento) return { exito: false, mensaje: "Seleccione trabajador y fecha antes de guardar." }; const r = await guardarDocumentoClinicoServicio(id, datos, u.id, finalizar); revalidatePath("/documentos-clinicos"); revalidatePath(`/trabajadores/${datos.trabajadorId}`); return { exito: true, datos: { id: r.id } }; } catch (e) { if (e instanceof z.ZodError) return { exito: false, mensaje: "Revise los campos.", erroresCampos: z.flattenError(e).fieldErrors as Record<string, string[]> }; return { exito: false, mensaje: e instanceof Error ? e.message : "No fue posible guardar." }; } }
export async function anularDocumentoClinicoAccion(id: string, motivo: string): Promise<Resultado<{ id: string }>> { try { const u = await requerirPermiso("documento-clinico.anular"); if (motivo.trim().length < 5) return { exito: false, mensaje: "Indique un motivo de al menos 5 caracteres." }; await anularDocumentoClinicoServicio(id, motivo.trim(), u.id); revalidatePath("/documentos-clinicos"); return { exito: true, datos: { id } }; } catch (e) { return { exito: false, mensaje: e instanceof Error ? e.message : "No fue posible anular." }; } }
