import type { Prisma } from "@/generated/prisma/client";
import { prisma } from "@/servicios/base-datos/prisma";
import type { DocumentoClinicoDetalleDto, DocumentoClinicoResumenDto } from "@/modulos/documentos-clinicos/tipos";
const iso = (d: Date | null) => d?.toISOString().slice(0, 10) ?? null;
export async function listarDocumentosClinicos(usuarioId: string, filtros: { trabajador?: string; fecha?: string; estado?: string; pagina?: number }) {
  const pagina = Math.max(1, filtros.pagina ?? 1); const porPagina = 25; const q = filtros.trabajador?.trim();
  const where: Prisma.DocumentoClinicoWhereInput = { empresa: { usuariosAutorizados: { some: { usuarioId } } }, ...(q ? { OR: [{ trabajadorNombreHistorico: { contains: q, mode: "insensitive" } }, { trabajadorDocumentoHistorico: { contains: q, mode: "insensitive" } }, { numeroDocumento: { contains: q, mode: "insensitive" } }] } : {}), ...(filtros.fecha ? { fechaDocumento: new Date(`${filtros.fecha}T00:00:00.000Z`) } : {}), ...(filtros.estado && ["BORRADOR", "FINALIZADO", "ANULADO"].includes(filtros.estado) ? { estado: filtros.estado as "BORRADOR" | "FINALIZADO" | "ANULADO" } : {}) };
  const [total, items] = await Promise.all([prisma.documentoClinico.count({ where }), prisma.documentoClinico.findMany({ where, orderBy: [{ fechaDocumento: "desc" }, { creadoEn: "desc" }], skip: (pagina - 1) * porPagina, take: porPagina })]);
  const documentos: DocumentoClinicoResumenDto[] = items.map((d) => ({ id: d.id, numeroDocumento: d.numeroDocumento, trabajadorId: d.trabajadorId, trabajador: d.trabajadorNombreHistorico, documento: d.trabajadorDocumentoHistorico, fecha: iso(d.fechaDocumento)!, empresa: d.empresaNombreHistorico, profesional: d.profesionalNombreHistorico, estado: d.estado }));
  return { documentos, total, pagina, totalPaginas: Math.max(1, Math.ceil(total / porPagina)) };
}
export async function consultarDocumentoClinico(usuarioId: string, id: string): Promise<DocumentoClinicoDetalleDto | null> {
  const d = await prisma.documentoClinico.findFirst({ where: { id, empresa: { usuariosAutorizados: { some: { usuarioId } } } }, include: { diagnosticos: { orderBy: { orden: "asc" } }, tratamientos: { orderBy: { orden: "asc" } } } }); if (!d) return null;
  return { id: d.id, numeroDocumento: d.numeroDocumento, trabajadorId: d.trabajadorId, trabajador: d.trabajadorNombreHistorico, documento: d.trabajadorDocumentoHistorico, fecha: iso(d.fechaDocumento)!, empresa: d.empresaNombreHistorico, profesional: d.profesionalNombreHistorico, estado: d.estado, fechaNacimiento: iso(d.trabajadorNacimientoHistorico), departamento: d.departamentoNombreHistorico, motivoConsulta: d.motivoConsulta, evolucion: d.evolucion, observaciones: d.observaciones, registroDiarioId: d.registroDiarioId, diagnosticos: d.diagnosticos.map((x) => ({ id: x.id, codigo: x.codigoHistorico, descripcion: x.descripcionHistorica, tipo: x.tipo, observacion: x.observacion })), tratamientos: d.tratamientos.map((x) => ({ id: x.id, nombre: x.nombreHistorico, concentracion: x.concentracion, dosis: x.dosis, cantidad: x.cantidad, frecuencia: x.frecuencia, intervaloHoras: x.intervaloHoras, duracion: x.duracion, via: x.via, indicaciones: x.indicaciones, observaciones: x.observaciones })), motivoAnulacion: d.motivoAnulacion };
}
export async function obtenerDocumentoClinicoFormulario(usuarioId: string, id: string) { return prisma.documentoClinico.findFirst({ where: { id, empresa: { usuariosAutorizados: { some: { usuarioId } } } }, include: { diagnosticos: { orderBy: { orden: "asc" } }, tratamientos: { orderBy: { orden: "asc" } } } }); }
