"use client";
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { zodResolver } from "@hookform/resolvers/zod";
import { Plus, Search, Trash2 } from "lucide-react";
import { useFieldArray, useForm, useWatch } from "react-hook-form";
import { Button } from "@/componentes/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/componentes/ui/card";
import { Input } from "@/componentes/ui/input";
import { Textarea } from "@/componentes/ui/textarea";
import { EtiquetaCampo } from "@/componentes/ui/etiqueta-campo";
import { BarraAccionesFormulario } from "@/componentes/formularios/barra-acciones-formulario";
import { BotonRegresar } from "@/componentes/navegacion/boton-regresar";
import { useProteccionSalida } from "@/componentes/formularios/use-proteccion-salida";
import { useToastGuardado } from "@/componentes/retroalimentacion/toast-guardado";
import { BuscadorCie10 } from "@/modulos/catalogo-cie10/componentes/buscador-cie10";
import { buscarTrabajadoresDocumentoAccion, guardarDocumentoClinicoAccion } from "@/modulos/documentos-clinicos/acciones/documentos-clinicos.acciones";
import { documentoClinicoBorradorSchema, documentoClinicoFinalizarSchema, type DatosDocumentoClinico, type EntradaDocumentoClinico } from "@/modulos/documentos-clinicos/validaciones/documento-clinico.schema";
import type { TrabajadorRegistroDto } from "@/modulos/registro-diario/tipos";
import { coincideAlergiaMedicamento } from "@/modulos/evaluaciones-medicas/utilidades/normalizar-sustancia";

function Campo({ etiqueta, requerido, error, children }: { etiqueta: string; requerido?: boolean; error?: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium"><EtiquetaCampo etiqueta={etiqueta} required={requerido} />{children}{error && <span className="text-xs text-destructive">{error}</span>}</label>; }

export function FormularioDocumentoClinico({ documentoId, trabajadorInicial, valores }: { documentoId?: string; trabajadorInicial?: TrabajadorRegistroDto | null; valores: EntradaDocumentoClinico }) {
  const router = useRouter();
  const [pendiente, iniciar] = useTransition(); const [trabajador, setTrabajador] = useState(trabajadorInicial ?? null); const [busqueda, setBusqueda] = useState(""); const [resultados, setResultados] = useState<TrabajadorRegistroDto[]>([]); const [mensaje, setMensaje] = useState("");
  const form = useForm<EntradaDocumentoClinico, unknown, DatosDocumentoClinico>({ resolver: zodResolver(documentoClinicoBorradorSchema), defaultValues: valores }); const diagnosticos = useFieldArray({ control: form.control, name: "diagnosticos" }); const tratamientos = useFieldArray({ control: form.control, name: "tratamientos" }); const tratamientosActuales = useWatch({ control: form.control, name: "tratamientos" }) ?? []; const errores = form.formState.errors; const { mostrar: mostrarGuardado } = useToastGuardado(); useProteccionSalida(form.formState.isDirty && !pendiente);
  useEffect(() => { if (busqueda.trim().length < 2) return; const t = setTimeout(async () => setResultados(await buscarTrabajadoresDocumentoAccion(busqueda)), 300); return () => clearTimeout(t); }, [busqueda]);
  
  const guardar = (finalizar: boolean) => form.handleSubmit((datos) => iniciar(async () => { setMensaje(""); const v = (finalizar ? documentoClinicoFinalizarSchema : documentoClinicoBorradorSchema).safeParse(datos); if (!v.success) { v.error.issues.forEach((i) => form.setError(i.path.join(".") as keyof EntradaDocumentoClinico, { message: i.message })); setMensaje("Revise los campos obligatorios."); return; } const r = await guardarDocumentoClinicoAccion(documentoId ?? null, v.data, finalizar); if (!r.exito) { setMensaje(r.mensaje ?? "No fue posible guardar."); return; } mostrarGuardado(finalizar ? "Documento finalizado" : "Borrador guardado"); router.push(finalizar ? `/documentos-clinicos/${r.datos?.id}` : `/documentos-clinicos/${r.datos?.id}/editar?guardado=1`); }))();
  return <form className="space-y-5 pb-56 sm:pb-28" onSubmit={(e) => e.preventDefault()} noValidate>
    <Card><CardHeader><CardTitle>Datos</CardTitle></CardHeader><CardContent className="space-y-4">{!trabajador && <div className="relative"><Search className="absolute left-3 top-3 size-4" aria-hidden /><Input className="pl-9" value={busqueda} onChange={(e) => setBusqueda(e.target.value)} placeholder="Buscar trabajador por nombre o cédula" aria-label="Buscar trabajador" />{busqueda.trim().length >= 2 && resultados.length > 0 && <div role="listbox" className="absolute z-20 mt-1 max-h-64 w-full overflow-auto rounded-md border bg-popover shadow">{resultados.map((t) => <button role="option" aria-selected="false" type="button" key={t.id} className="min-h-11 w-full border-b p-3 text-left hover:bg-accent" onClick={() => { setTrabajador(t); form.setValue("trabajadorId", t.id, { shouldDirty: true }); setResultados([]); setBusqueda(""); }}><b>{t.nombreCompleto}</b><br /><span className="text-sm text-muted-foreground">{t.numeroDocumento} · {t.empresa}</span></button>)}</div>}</div>}{trabajador && <div className="grid gap-3 rounded border p-4 sm:grid-cols-2 lg:grid-cols-4"><p><b>Trabajador</b><br />{trabajador.nombreCompleto}</p><p><b>Cédula</b><br />{trabajador.numeroDocumento}</p><p><b>Nacimiento / edad</b><br />{trabajador.fechaNacimiento ?? "—"} · {trabajador.edad ?? "—"} años</p><p><b>Empresa / departamento</b><br />{trabajador.empresa} · {trabajador.departamento}</p></div>}{trabajador && trabajador.alergias.length > 0 && <div role="alert" className="rounded border border-amber-500 bg-amber-500/10 p-3 text-sm"><b>Alergias activas:</b> {trabajador.alergias.map((a) => `${a.sustancia} (${a.severidad})`).join(", ")}</div>}<Campo etiqueta="Fecha" requerido error={errores.fechaDocumento?.message}><Input type="date" required aria-required="true" {...form.register("fechaDocumento")} /></Campo></CardContent></Card>
    <Card><CardHeader><CardTitle>Motivo de consulta</CardTitle></CardHeader><CardContent><Campo etiqueta="Motivo de consulta" requerido error={errores.motivoConsulta?.message}><Textarea className="min-h-32" required aria-required="true" {...form.register("motivoConsulta")} /></Campo></CardContent></Card>
    <Card><CardHeader><CardTitle>Evolución</CardTitle></CardHeader><CardContent className="space-y-4"><Campo etiqueta="Evolución clínica" requerido error={errores.evolucion?.message}><Textarea className="min-h-44" required aria-required="true" {...form.register("evolucion")} /></Campo><Campo etiqueta="Observaciones"><Textarea className="min-h-24" {...form.register("observaciones")} /></Campo></CardContent></Card>
    <Card><CardHeader><CardTitle>Diagnósticos</CardTitle></CardHeader><CardContent className="space-y-3"><BuscadorCie10 onSeleccionar={(r) => { if (!(form.getValues("diagnosticos") ?? []).some((d) => d.enfermedadId === r.id)) diagnosticos.append({ enfermedadId: r.id, codigo: r.codigo, descripcion: r.descripcion, tipo: "PRESUNTIVO", observacion: "" }); }} />{diagnosticos.fields.map((d, i) => <div key={d.id} className="grid gap-2 rounded border p-3 sm:grid-cols-[1fr_180px_auto]"><p>{d.codigo} — {d.descripcion}</p><select className="h-10 rounded border bg-background px-2" {...form.register(`diagnosticos.${i}.tipo`)}><option value="PRESUNTIVO">Presuntivo</option><option value="DEFINITIVO">Definitivo</option></select><Button type="button" size="icon" variant="ghost" aria-label="Eliminar diagnóstico" onClick={() => diagnosticos.remove(i)}><Trash2 /></Button></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Tratamiento</CardTitle></CardHeader><CardContent className="space-y-4">{tratamientos.fields.map((t, i) => { const actual = tratamientosActuales[i]; const alergia = trabajador?.alergias.find((a) => coincideAlergiaMedicamento(actual?.nombre ?? "", a.sustancia)); return <div key={t.id} className="space-y-3 rounded border p-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Campo etiqueta="Medicación" requerido><Input required {...form.register(`tratamientos.${i}.nombre`)} /></Campo><Campo etiqueta="Concentración"><Input {...form.register(`tratamientos.${i}.concentracion`)} /></Campo><Campo etiqueta="Dosis" requerido><Input required {...form.register(`tratamientos.${i}.dosis`)} /></Campo><Campo etiqueta="Cantidad" requerido><Input required {...form.register(`tratamientos.${i}.cantidad`)} /></Campo><Campo etiqueta="Frecuencia"><Input {...form.register(`tratamientos.${i}.frecuencia`)} /></Campo><Campo etiqueta="Cada cuántas horas"><Input type="number" {...form.register(`tratamientos.${i}.intervaloHoras`)} /></Campo><Campo etiqueta="Duración"><Input {...form.register(`tratamientos.${i}.duracion`)} /></Campo><Campo etiqueta="Vía"><Input {...form.register(`tratamientos.${i}.via`)} /></Campo><Campo etiqueta="Indicaciones"><Textarea {...form.register(`tratamientos.${i}.indicaciones`)} /></Campo><Campo etiqueta="Observaciones"><Textarea {...form.register(`tratamientos.${i}.observaciones`)} /></Campo></div>{alergia && <div role="alert" className="space-y-2 rounded border border-red-500 bg-red-500/10 p-3 text-sm"><b>Alerta: posible coincidencia con alergia a {alergia.sustancia} ({alergia.severidad}).</b><label className="flex gap-2"><input type="checkbox" {...form.register(`tratamientos.${i}.alertaAlergiaConfirmada`)} />Confirmo continuar bajo criterio clínico.</label><Campo etiqueta="Justificación clínica" requerido><Textarea {...form.register(`tratamientos.${i}.justificacionAlergia`)} /></Campo></div>}<Button type="button" variant="ghost" onClick={() => tratamientos.remove(i)}><Trash2 aria-hidden /> Eliminar tratamiento</Button></div>; })}<Button type="button" variant="outline" onClick={() => tratamientos.append({ nombre: "", concentracion: "", dosis: "", cantidad: "", frecuencia: "", intervaloHoras: "", duracion: "", via: "", indicaciones: "", observaciones: "", alertaAlergiaConfirmada: false, justificacionAlergia: "" })}><Plus aria-hidden /> Agregar tratamiento</Button></CardContent></Card>
    {mensaje && <p role="alert" className="text-sm text-destructive">{mensaje}</p>}<BarraAccionesFormulario rutaRegreso="/documentos-clinicos" cancelar={<BotonRegresar etiqueta="Volver al listado" rutaRespaldo="/documentos-clinicos" />} secundario={<Button type="button" variant="outline" disabled={pendiente} onClick={() => guardar(false)}>Guardar borrador</Button>} principal={<Button type="button" disabled={pendiente} onClick={() => guardar(true)}>Finalizar documento</Button>} />
  </form>;
}
